(function registerBattleElements(){
  "use strict";
  const TILE=32, VIEW=["sceneEpoch","visualEpoch","paused","viewportWidth","viewportHeight","barHeight","contentWidth","contentHeight","columns","rows","logicalWidth","logicalHeight","scaleX","scaleY","mapWidth","mapHeight","cameraX","cameraY","tileset","autotiles","tiles"], ACTOR=["sceneEpoch","visualEpoch","paused","actorId","tileX","tileY","direction","sprite","life","motion"], EFFECTS=["sceneEpoch","visualEpoch","paused","effectStarts"], HUD=["sceneEpoch","visualEpoch","actors"];
  const QUARTERS=[[27,28,33,34],[5,28,33,34],[27,6,33,34],[5,6,33,34],[27,28,33,12],[5,28,33,12],[27,6,33,12],[5,6,33,12],[27,28,11,34],[5,28,11,34],[27,6,11,34],[5,6,11,34],[27,28,11,12],[5,28,11,12],[27,6,11,12],[5,6,11,12],[25,26,31,32],[25,6,31,32],[25,26,31,12],[25,6,31,12],[15,16,21,22],[15,16,21,12],[15,16,11,22],[15,16,11,12],[29,30,35,36],[29,30,11,36],[5,30,35,36],[5,30,11,36],[39,40,45,46],[5,40,45,46],[39,6,45,46],[5,6,45,46],[25,30,31,36],[15,16,45,46],[13,14,19,20],[13,14,19,12],[17,18,23,24],[17,18,11,24],[41,42,47,48],[5,42,47,48],[37,38,43,44],[37,6,43,44],[13,18,19,24],[13,14,43,44],[37,42,43,48],[17,18,47,48],[13,18,43,48],[1,2,7,8]];
  const exact=(v,k)=>v!==null&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(x=>Object.prototype.hasOwnProperty.call(v,x));
  const integer=(v,min=0)=>Number.isSafeInteger(v)&&v>=min;
  const scalar=v=>{if(typeof v!=="string")return false;for(let i=0;i<v.length;i+=1){const u=v.charCodeAt(i);if(u>=0xd800&&u<=0xdbff){const n=v.charCodeAt(i+1);if(!(n>=0xdc00&&n<=0xdfff))return false;i+=1}else if(u>=0xdc00&&u<=0xdfff)return false}return true};
  const actorId=v=>scalar(v)&&new TextEncoder().encode(v).byteLength>=1&&new TextEncoder().encode(v).byteLength<=115;
  const ref=v=>exact(v,["namespace","key","contentVersion"])&&[v.namespace,v.key,v.contentVersion].every(x=>scalar(x)&&x.length>0);
  const fail=m=>{throw new TypeError(m)};
  const sameRef=(a,b)=>a.namespace===b.namespace&&a.key===b.key&&a.contentVersion===b.contentVersion;
  const sameMotion=(a,b)=>a.id===b.id&&a.fromWorldX===b.fromWorldX&&a.fromWorldY===b.fromWorldY&&a.toWorldX===b.toWorldX&&a.toWorldY===b.toWorldY&&a.durationMs===b.durationMs;
  const sameEffect=(a,b)=>a.effectId===b.effectId&&a.result===b.result&&sameRef(a.image,b.image)&&a.worldX===b.worldX&&a.worldY===b.worldY&&a.fadeInMs===b.fadeInMs&&a.holdMs===b.holdMs&&a.fadeOutMs===b.fadeOutMs;
  function assertView(d){
    if(!exact(d,VIEW)||!integer(d.sceneEpoch,1)||!integer(d.visualEpoch,1)||typeof d.paused!=="boolean"||!integer(d.viewportWidth,1)||!integer(d.viewportHeight,1))fail("Invalid BattleViewRenderData");
    const bar=d.viewportHeight<480?24:d.viewportHeight<720?32:48,contentHeight=d.viewportHeight-bar,rawRows=Math.ceil(contentHeight/TILE),rows=Math.min(33,Math.max(14,rawRows)),columns=rawRows<14||rawRows>33?Math.max(1,Math.round(rows*d.viewportWidth/contentHeight)):Math.ceil(d.viewportWidth/TILE);
    if(contentHeight<=0||d.barHeight!==bar||d.contentWidth!==d.viewportWidth||d.contentHeight!==contentHeight||d.columns!==columns||d.rows!==rows||d.logicalWidth!==columns*TILE||d.logicalHeight!==rows*TILE||d.scaleX!==d.contentWidth/d.logicalWidth||d.scaleY!==d.contentHeight/d.logicalHeight||!integer(d.mapWidth,1)||!integer(d.mapHeight,1)||!integer(d.cameraX)||!integer(d.cameraY)||d.cameraX>Math.max(d.mapWidth*TILE-d.logicalWidth,0)||d.cameraY>Math.max(d.mapHeight*TILE-d.logicalHeight,0)||!ref(d.tileset)||!Array.isArray(d.autotiles)||d.autotiles.length!==7||!d.autotiles.every(x=>x===null||ref(x))||!Array.isArray(d.tiles))fail("Invalid BattleViewRenderData");
    let last;for(const t of d.tiles){if(!Array.isArray(t)||t.length!==5||!integer(t[0])||t[0]>=d.mapWidth||!integer(t[1])||t[1]>=d.mapHeight||![0,1,2].includes(t[2])||!integer(t[3],48)||!integer(t[4]))fail("Invalid BattleViewRenderData");if(last&&(t[2]<last[2]||(t[2]===last[2]&&(t[1]<last[1]||(t[1]===last[1]&&t[0]<=last[0])))))fail("Invalid tile order");last=t}
  }
  function assertActor(d){if(!exact(d,ACTOR)||!integer(d.sceneEpoch,1)||!integer(d.visualEpoch,1)||typeof d.paused!=="boolean"||!actorId(d.actorId)||!integer(d.tileX)||!integer(d.tileY)||![2,4,6,8].includes(d.direction)||!ref(d.sprite)||!["alive","dead"].includes(d.life)||!(d.motion===null||exact(d.motion,["id","fromWorldX","fromWorldY","toWorldX","toWorldY","durationMs"])&&integer(d.motion.id,1)&&[d.motion.fromWorldX,d.motion.fromWorldY,d.motion.toWorldX,d.motion.toWorldY].every(v=>integer(v))&&integer(d.motion.durationMs,1)))fail("Invalid BattleActorRenderData")}
  function assertEffects(d){if(!exact(d,EFFECTS)||!integer(d.sceneEpoch,1)||!integer(d.visualEpoch,1)||typeof d.paused!=="boolean"||!Array.isArray(d.effectStarts))fail("Invalid BattleEffectsRenderData");const ids=new Set();for(const e of d.effectStarts){if(!exact(e,["effectId","result","image","worldX","worldY","fadeInMs","holdMs","fadeOutMs"])||!scalar(e.effectId)||e.effectId.length===0||ids.has(e.effectId)||!["hit","immune"].includes(e.result)||!ref(e.image)||![e.worldX,e.worldY].every(v=>Number.isFinite(v)&&v>=0)||![e.fadeInMs,e.holdMs,e.fadeOutMs].every(v=>integer(v))||e.fadeInMs+e.holdMs+e.fadeOutMs<=0)fail("Invalid BattleEffectRenderStart");ids.add(e.effectId)}}
  function assertHud(d){if(!exact(d,HUD)||!integer(d.sceneEpoch,1)||!integer(d.visualEpoch,1)||!Array.isArray(d.actors))fail("Invalid BattleHudRenderData");const ids=new Set();for(const a of d.actors){if(!exact(a,["actorId","team","hp","maxHp"])||!actorId(a.actorId)||ids.has(a.actorId)||!["ally","enemy"].includes(a.team)||!integer(a.hp)||!integer(a.maxHp,1)||a.hp>a.maxHp)fail("Invalid BattleHudRenderData");ids.add(a.actorId)}}
  function resourceUrl(resource){if(!resource||!(resource.bytes instanceof Uint8Array)||typeof resource.mime!=="string"||resource.mime.length===0)fail("Invalid browser resource");return URL.createObjectURL(new Blob([resource.bytes],{type:resource.mime}))}
  const imageCaches=new WeakMap();
  const resourceIdentity=r=>`${r.namespace.length}:${r.namespace}${r.key.length}:${r.key}${r.contentVersion.length}:${r.contentVersion}`;
  function image(resources,r){let cache=imageCaches.get(resources);if(!cache){cache=new Map();imageCaches.set(resources,cache)}const key=resourceIdentity(r),known=cache.get(key);if(known?.image)return Promise.resolve(known.image);if(known?.promise)return known.promise;const entry={};const promise=(async()=>{const value=await resources.resource(r.namespace,r.key,r.contentVersion);const url=resourceUrl(value);try{const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});return img}finally{URL.revokeObjectURL(url)}})();entry.promise=promise;cache.set(key,entry);return promise.then(img=>{if(cache.get(key)===entry)cache.set(key,{image:img});return img},error=>{if(cache.get(key)===entry)cache.delete(key);throw error})}
  class BattleView extends HTMLElement{
    constructor(){super();const s=this.attachShadow({mode:"open"});s.innerHTML='<style>:host{display:block;position:relative;overflow:hidden;background:#161b25}.stage{position:absolute;left:0;top:0;transform-origin:0 0;overflow:hidden}.world{position:absolute;transform-origin:0 0}.tiles{position:absolute;inset:0}.hud{position:absolute;left:0;right:0;bottom:0}</style><div class="stage"><div class="world"><div class="tiles"></div><slot name="world"></slot></div></div><div class="hud"><slot name="hud"></slot></div>';this._stage=s.querySelector(".stage");this._world=s.querySelector(".world");this._tiles=s.querySelector(".tiles");this._sequence=0;this._data=null;this._animationStart=performance.now();this._pausedAt=null;this._pauseTotal=0;this._raf=0}
    receiveRenderContext(c){if(!c||!c.resources||typeof c.resources.resource!=="function")fail("Battle presentation requires resources");this._resources=c.resources}
    receiveRenderData(d){assertView(d);const now=performance.now();if(d.paused&&this._pausedAt===null)this._pausedAt=now;if(!d.paused&&this._pausedAt!==null){this._pauseTotal+=now-this._pausedAt;this._pausedAt=null}this._data=d;const seq=++this._sequence;this.style.width=`${d.viewportWidth}px`;this.style.height=`${d.viewportHeight}px`;this._stage.style.width=`${d.logicalWidth}px`;this._stage.style.height=`${d.logicalHeight}px`;this._stage.style.transform=`scale(${d.scaleX},${d.scaleY})`;this.shadowRoot.querySelector(".hud").style.height=`${d.barHeight}px`;const ox=Math.max(0,(d.logicalWidth-d.mapWidth*32)/2),oy=Math.max(0,(d.logicalHeight-d.mapHeight*32)/2);this._world.style.transform=`translate(${ox-d.cameraX}px,${oy-d.cameraY}px)`;this._prepareTiles(d,seq)}
    async _prepareTiles(d,seq){const used=new Set(d.tiles.filter(t=>t[3]>=48&&t[3]<384).map(t=>Math.floor((t[3]-48)/48)));let tileset=null;try{tileset=await image(this._resources,d.tileset)}catch{}const autotiles=new Map();await Promise.all([...used].map(async slot=>{const r=d.autotiles[slot];if(!r)return;try{const img=await image(this._resources,r);const name=r.key.slice(r.key.lastIndexOf("/")+1),match=/\[\s*(\d+)\s*\]\s*$/.exec(name),ticks=match?Number(match[1]):5;if(Number.isSafeInteger(ticks)&&ticks>0)autotiles.set(slot,{img,duration:ticks*50,layout:img.height===32&&img.width%32===0?"cell":img.height===128&&img.width%96===0?"block":"invalid"})}catch{}}));if(seq!==this._sequence)return;this._prepared={tileset,autotiles};this._paintTiles(seq)}
    _paintTiles(seq){cancelAnimationFrame(this._raf);if(seq!==this._sequence||!this._prepared)return;const d=this._data,now=this._pausedAt??performance.now(),elapsed=Math.max(0,now-this._animationStart-this._pauseTotal);this._tiles.replaceChildren();let animated=false;for(const [x,y,,id,depth] of d.tiles){const c=document.createElement("canvas");c.width=32;c.height=32;c.style.cssText=`position:absolute;left:${x*32}px;top:${y*32}px;z-index:${depth*2};image-rendering:pixelated`;const g=c.getContext("2d");g.imageSmoothingEnabled=false;if(id>=384&&this._prepared.tileset&&((id-384)%8)*32+32<=this._prepared.tileset.width&&Math.floor((id-384)/8)*32+32<=this._prepared.tileset.height)g.drawImage(this._prepared.tileset,((id-384)%8)*32,Math.floor((id-384)/8)*32,32,32,0,0,32,32);else if(id>=48&&id<384){const slot=Math.floor((id-48)/48),variant=(id-48)%48,a=this._prepared.autotiles.get(slot);if(a&&a.layout!=="invalid"){const frames=a.layout==="cell"?a.img.width/32:a.img.width/96,frame=Math.floor(elapsed/a.duration)%frames;animated=animated||frames>1;if(a.layout==="cell")g.drawImage(a.img,frame*32,0,32,32,0,0,32,32);else QUARTERS[variant].forEach((q,i)=>{const n=q-1;g.drawImage(a.img,frame*96+(n%6)*16,Math.floor(n/6)*16,16,16,(i%2)*16,Math.floor(i/2)*16,16,16)})}else{g.fillStyle="#b45cff";g.fillRect(0,0,32,32)}}else{g.fillStyle="#ff3f66";g.fillRect(0,0,32,32)}this._tiles.append(c)}if(animated&&!d.paused)this._raf=requestAnimationFrame(()=>this._paintTiles(seq))}
    disconnectedCallback(){cancelAnimationFrame(this._raf);this._sequence++}
  }
  class BattleActor extends HTMLElement{
    constructor(){super();const s=this.attachShadow({mode:"open"});s.innerHTML='<style>:host{position:absolute;display:block;image-rendering:pixelated}canvas{display:block;image-rendering:pixelated}.fallback{width:32px;height:32px;background:repeating-linear-gradient(45deg,#f0c 0 8px,#222 8px 16px)}</style><canvas></canvas><div class="fallback" hidden></div>';this._canvas=s.querySelector("canvas");this._fallback=s.querySelector(".fallback");this._ctx=this._canvas.getContext("2d");this._motion=null;this._pausedAt=null;this._pauseTotal=0;this._raf=0;this._seq=0}
    receiveRenderContext(c){if(!c||!c.resources||typeof c.resources.resource!=="function")fail("Battle actor requires resources");this._resources=c.resources}
    receiveRenderData(d){assertActor(d);const motion=d.life==="alive"?d.motion:null;if(this._motion&&motion&&this._motion.id===motion.id&&!sameMotion(this._motion.fact,motion))fail("Conflicting actor motion");if(!motion)this._motion=null;else if(!this._motion||this._motion.id!==motion.id)this._motion={id:motion.id,fact:motion,started:performance.now(),pauseTotal:0,pausedAt:null};if(d.paused&&this._motion&&this._motion.pausedAt===null)this._motion.pausedAt=performance.now();if(!d.paused&&this._motion?.pausedAt!==null&&this._motion){this._motion.pauseTotal+=performance.now()-this._motion.pausedAt;this._motion.pausedAt=null}this._data=d;const seq=++this._seq;image(this._resources,d.sprite).then(img=>{if(seq===this._seq){this._img=img;this._fallback.hidden=true;this._canvas.hidden=false;this._paint()}}).catch(()=>{if(seq===this._seq){this._img=null;this._canvas.hidden=true;this._fallback.hidden=false;this._paint()}});this._paint()}
    _paint(){cancelAnimationFrame(this._raf);if(!this._data)return;const d=this._data,m=d.life==="alive"?d.motion:null,now=this._motion?.pausedAt??performance.now(),p=m&&this._motion?Math.min(1,Math.max(0,(now-this._motion.started-this._motion.pauseTotal)/m.durationMs)):1;const wx=m?m.fromWorldX+(m.toWorldX-m.fromWorldX)*p:d.tileX*32,wy=m?m.fromWorldY+(m.toWorldY-m.fromWorldY)*p:d.tileY*32;let fw=32,fh=32;if(this._img){fw=this._img.width/4;fh=this._img.height/4;if(!Number.isInteger(fw)||!Number.isInteger(fh)||fw<=0||fh<=0){this._img=null;this._canvas.hidden=true;this._fallback.hidden=false;fw=32;fh=32}else{const pattern=m?(p<.5?1:2):0;this._canvas.width=fw;this._canvas.height=fh;this._ctx.imageSmoothingEnabled=false;this._ctx.clearRect(0,0,fw,fh);this._ctx.drawImage(this._img,pattern*fw,((d.direction-2)/2)*fh,fw,fh,0,0,fw,fh)}}this.style.left=`${wx+(32-fw)/2}px`;this.style.top=`${wy+32-fh}px`;this.style.opacity=d.life==="dead"?"0.5":"1";this.style.zIndex=String((Math.round(wy)+32+(fh>32?31:0))*2+1);if(m&&p<1&&!d.paused)this._raf=requestAnimationFrame(()=>this._paint())}
    disconnectedCallback(){cancelAnimationFrame(this._raf);this._seq++}
  }
  class BattleEffects extends HTMLElement{
    constructor(){super();const s=this.attachShadow({mode:"open"});s.innerHTML='<style>:host{position:absolute;inset:0;z-index:2147483000;pointer-events:none}.effect{position:absolute;transform:translate(-50%,-50%);image-rendering:pixelated}</style><div></div>';this._root=s.querySelector("div");this._active=new Map();this._seen=new Map();this._paused=false;this._pausedAt=null;this._raf=0}
    receiveRenderContext(c){if(!c||!c.resources||typeof c.resources.resource!=="function")fail("Battle effects require resources");this._resources=c.resources}
    receiveRenderData(d){assertEffects(d);for(const start of d.effectStarts){const seen=this._seen.get(start.effectId);if(seen!==undefined&&!sameEffect(seen,start))fail("Conflicting BattleEffect id")}const now=performance.now();if(d.paused&&!this._paused)this._pausedAt=now;if(!d.paused&&this._paused){for(const e of this._active.values())e.started+=now-this._pausedAt;this._pausedAt=null}this._paused=d.paused;for(const start of d.effectStarts){if(this._seen.has(start.effectId))continue;this._seen.set(start.effectId,start);const node=document.createElement("canvas");node.className="effect";node.style.left=`${start.worldX}px`;node.style.top=`${start.worldY}px`;this._root.append(node);const entry={start,node,started:this._paused?this._pausedAt:now};this._active.set(start.effectId,entry);image(this._resources,start.image).then(img=>{if(this._active.get(start.effectId)===entry){node.width=img.width;node.height=img.height;const context=node.getContext("2d");context.imageSmoothingEnabled=false;context.drawImage(img,0,0)}}).catch(()=>{if(this._active.get(start.effectId)===entry){node.remove();this._active.delete(start.effectId)}})}this._tick()}
    _tick(){cancelAnimationFrame(this._raf);const now=this._paused?this._pausedAt:performance.now();for(const [id,e] of this._active){const t=Math.max(0,now-e.started),total=e.start.fadeInMs+e.start.holdMs+e.start.fadeOutMs,max=e.start.result==="immune"?.6:1;if(t>=total){e.node.remove();this._active.delete(id);continue}e.node.style.opacity=String(t<e.start.fadeInMs?(e.start.fadeInMs?max*t/e.start.fadeInMs:max):t<e.start.fadeInMs+e.start.holdMs?max:e.start.fadeOutMs?max*(total-t)/e.start.fadeOutMs:0)}if(this._active.size&&!this._paused)this._raf=requestAnimationFrame(()=>this._tick())}
    disconnectedCallback(){cancelAnimationFrame(this._raf);for(const e of this._active.values())e.node.remove();this._active.clear();this._seen.clear()}
  }
  class BattleHud extends HTMLElement{
    constructor(){super();const s=this.attachShadow({mode:"open"});s.innerHTML='<style>:host{display:block;background:#111d;color:#fff;font:16px/1.2 system-ui}.row{height:100%;display:flex;align-items:center;justify-content:space-between;padding:0 18px;box-sizing:border-box}.enemy{text-align:right}</style><div class="row"><span class="ally"></span><span class="enemy"></span></div>';this._ally=s.querySelector(".ally");this._enemy=s.querySelector(".enemy")}
    receiveRenderContext(){}
    receiveRenderData(d){assertHud(d);const sorted=[...d.actors].sort((a,b)=>a.team===b.team?(a.actorId<b.actorId?-1:a.actorId>b.actorId?1:0):a.team==="ally"?-1:1);this._ally.textContent=sorted.filter(a=>a.team==="ally").map(a=>`Ally ${a.hp} / ${a.maxHp}`).join(" · ");this._enemy.textContent=sorted.filter(a=>a.team==="enemy").map(a=>`Enemy ${a.hp} / ${a.maxHp}`).join(" · ");const view=this.getRootNode().host?.shadowRoot;const slot=this.parentElement?.shadowRoot;void view;void slot}
  }
  const owned=["lr-battle-view","lr-battle-actor","lr-battle-effects","lr-battle-hud"];
  if(owned.some(tag=>customElements.get(tag)!==undefined))fail("Battle custom element already registered");
  customElements.define("lr-battle-view",BattleView);customElements.define("lr-battle-actor",BattleActor);customElements.define("lr-battle-effects",BattleEffects);customElements.define("lr-battle-hud",BattleHud);
})();
