import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  title: 'LoomRealm',
  description: 'LoomRealm 分层设计文档',
  base: '/loom-realm/',
  cleanUrls: true,
  lastUpdated: true,
  markdown: { lineNumbers: true },

  themeConfig: {
    siteTitle: 'LoomRealm',
    nav: [
      { text: '首页', link: '/' },
      { text: '阅读指南', link: '/README' },
      { text: '系统架构', link: '/10-architecture/system-overview' },
      { text: '平台组合', link: '/10-architecture/platform-composition-system' },
      { text: '正式契约', link: '/15-contracts/README' },
      { text: '模块设计', link: '/20-modules/README' },
      { text: '实施计划', link: '/30-implementation/README' },
    ],

    sidebar: [
      {
        text: '开始',
        items: [
          { text: '文档首页', link: '/' },
          { text: '阅读指南', link: '/README' },
        ],
      },
      {
        text: '00 · 产品总览',
        items: [
          { text: '产品设计总览', link: '/00-overview/product-vision' },
          { text: '文档分层与变更规则', link: '/00-overview/document-governance' },
        ],
      },
      {
        text: '10 · 系统架构',
        items: [
          { text: '系统架构总览', link: '/10-architecture/system-overview' },
          { text: '平台组合系统', link: '/10-architecture/platform-composition-system' },
          { text: '运行承载系统', link: '/10-architecture/runtime-hosting-system' },
          { text: '栈式运行系统', link: '/10-architecture/stack-runtime-system' },
          { text: '通信系统', link: '/10-architecture/communication-system' },
          { text: '渲染系统', link: '/10-architecture/rendering-system' },
          { text: '模块子系统模型', link: '/10-architecture/subsystem-model' },
          { text: '运行时启动与连接建立', link: '/10-architecture/runtime-bootstrap-system' },
          { text: 'Renderer–Subsystem 协议分层', link: '/10-architecture/renderer-subsystem-protocol-layers' },
          { text: '存储与内容系统', link: '/10-architecture/storage-system' },
        ],
      },
      {
        text: '15 · 正式契约',
        items: [
          { text: '契约目录', link: '/15-contracts/README' },
          { text: 'Game Package v1', link: '/15-contracts/game-package-v1' },
          { text: 'Hostra Game Launcher / Node Runner v1', link: '/15-contracts/nodejs-launcher-profile-v1' },
          { text: 'PWA Game Launcher / Worker Runner v1', link: '/15-contracts/pwa-launcher-profile-v1' },
          { text: 'Subsystem Control v1', link: '/15-contracts/subsystem-control-protocol-v1' },
          { text: 'Runtime Control Profile v1', link: '/15-contracts/runtime-control-profile-v1' },
          { text: 'Frame / Call v1', link: '/15-contracts/frame-call-protocol-v1' },
          { text: 'Frame / Call v1 Conformance', link: '/15-contracts/frame-call-conformance-v1' },
          { text: 'Main ⇄ Renderer Control v1', link: '/15-contracts/main-renderer-control-v1' },
          { text: 'Renderer Data Profile v1', link: '/15-contracts/renderer-data-profile-v1' },
          { text: 'Renderer ⇄ Subsystem Data Connection v1', link: '/15-contracts/renderer-subsystem-data-connection-v1' },
          { text: 'User Input v1', link: '/15-contracts/user-input-v1' },
          { text: 'Render Update v1', link: '/15-contracts/render-update-v1' },
          { text: 'Content API v1', link: '/15-contracts/content-api-v1' },
        ],
      },
      {
        text: '20 · 模块设计',
        items: [
          { text: '模块目录', link: '/20-modules/README' },
          { text: '程序主系统', link: '/20-modules/main-system/README' },
          { text: 'Web Renderer', link: '/20-modules/web-renderer/README' },
          { text: 'Game Package', link: '/20-modules/game-package/README' },
          { text: 'FSDB Content Service', link: '/20-modules/fsdb-content-service/README' },
          { text: 'loom.map', link: '/20-modules/loom-map/README' },
          { text: 'Hostra Desktop Composition', link: '/20-modules/desktop-host/README' },
          { text: 'PWA Composition', link: '/20-modules/pwa-host/README' },
        ],
      },
      {
        text: '30 · 实施计划',
        items: [
          { text: '实施计划目录', link: '/30-implementation/README' },
          { text: '独立分包与发布架构', link: '/30-implementation/package-architecture' },
          { text: '仓库与目录方案', link: '/30-implementation/repository-layout' },
          { text: '测试策略', link: '/30-implementation/testing-strategy' },
          { text: '第一阶段交付计划', link: '/30-implementation/phase-1-delivery-plan' },
        ],
      },
      {
        text: '设计决策',
        collapsed: true,
        items: [
          { text: 'ADR 0001', link: '/decisions/0001-system-container-per-system-id' },
          { text: 'ADR 0002', link: '/decisions/0002-platform-transport-profiles' },
          { text: 'ADR 0003', link: '/decisions/0003-readonly-content-api' },
          { text: 'ADR 0004', link: '/decisions/0004-client-state-rendering-pipeline' },
          { text: 'ADR 0005', link: '/decisions/0005-game-entry-subsystem-launchers' },
          { text: 'ADR 0006', link: '/decisions/0006-frame-render-decoupling' },
          { text: 'ADR 0007 · Superseded', link: '/decisions/0007-subsystem-descriptor-mvp' },
          { text: 'ADR 0008 · Superseded', link: '/decisions/0008-desktop-nodejs-launcher-profile-v1' },
          { text: 'ADR 0009', link: '/decisions/0009-freeze-subsystem-control-protocol-v1' },
          { text: 'ADR 0010', link: '/decisions/0010-freeze-frame-call-protocol-v1-batch-a' },
          { text: 'ADR 0011', link: '/decisions/0011-freeze-frame-call-protocol-v1-batch-b' },
          { text: 'ADR 0012', link: '/decisions/0012-freeze-frame-call-protocol-v1-batch-c' },
          { text: 'ADR 0013', link: '/decisions/0013-freeze-frame-call-protocol-v1-batch-d' },
          { text: 'ADR 0014', link: '/decisions/0014-freeze-frame-call-protocol-v1-batch-e' },
          { text: 'ADR 0015', link: '/decisions/0015-freeze-frame-call-protocol-v1-batch-f' },
          { text: 'ADR 0016', link: '/decisions/0016-protocol-boundary-cleanup' },
          { text: 'ADR 0017', link: '/decisions/0017-system-level-platform-composition' },
          { text: 'ADR 0018 · current-v1 closure', link: '/decisions/0018-preimplementation-v1-closure' },
          { text: 'ADR 0019 · Platform Launch Boundary', link: '/decisions/0019-platform-launch-manifest-boundary' },
        ],
      },
    ],

    search: { provider: 'local' },
    socialLinks: [{ icon: 'github', link: 'https://github.com/lithdoo/loom-realm' }],
    editLink: {
      pattern: 'https://github.com/lithdoo/loom-realm/edit/main/doc/:path',
      text: '在 GitHub 上编辑此页',
    },
    outline: { level: [2, 3], label: '页面导航' },
    lastUpdated: {
      text: '最后更新',
      formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
    },
    docFooter: { prev: '上一篇', next: '下一篇' },
    footer: {
      message: 'LoomRealm documentation',
      copyright: 'Copyright © LoomRealm contributors',
    },
  },
})
